apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-datatorgetbackend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datatorgetbackend
  template:
    metadata:
      labels:
        app: datatorgetbackend
    spec:
      containers:
      - name: bokningsapi
        image: datatorgetpoc/bokningsapi
        resources:
          limits:
            memory: "64Mi"
            cpu: "250m"
        ports:
        - containerPort: 30001
        env:
        - name: MESSAGE_SERVICE_HOST
          value: svc-rabbitmq
        - name: MESSAGE_SERVICE_PORT
          value: "5672"
        - name: MESSAGE_SERVICE_USERNAME
          valueFrom:
            secretKeyRef:
              name: secrets-datatorgetbackend
              key: MESSAGE_SERVICE_USERNAME
        - name: MESSAGE_SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets-datatorgetbackend
              key: MESSAGE_SERVICE_PASSWORD
        - name: MESSAGE_SERVICE_EXCHANGE
          value: "bokning"
        - name: MESSAGE_SERVICE_ENABLED
          value: "True"
        - name: OAUTH_AUTHORITY
          value: "http://datatorget2.helsingborg.se:30099"

      - name: kundapi
        image: datatorgetpoc/kundapi
        resources:
          limits:
            memory: "64Mi"
            cpu: "250m"
        ports:
        - containerPort: 30002
        env:
        - name: MESSAGE_SERVICE_HOST
          value: svc-rabbitmq
        - name: MESSAGE_SERVICE_PORT
          value: "5672"
        - name: MESSAGE_SERVICE_USERNAME
          valueFrom:
            secretKeyRef:
              name: secrets-datatorgetbackend
              key: MESSAGE_SERVICE_USERNAME
        - name: MESSAGE_SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets-datatorgetbackend
              key: MESSAGE_SERVICE_PASSWORD
        - name: MESSAGE_SERVICE_EXCHANGE
          value: "kund"
        - name: MESSAGE_SERVICE_ENABLED
          value: "True"
        - name: OAUTH_AUTHORITY
          value: "http://datatorget2.helsingborg.se:30099"
          
      - name: kommunikationsapi
        image: datatorgetpoc/kommunikationsapi
        resources:
          limits:
            memory: "64Mi"
            cpu: "250m"
        ports:
        - containerPort: 30003
        env:
        - name: SMTP_SERVICE_HOST
          value: "smtp.sendgrid.net"
        - name: SMTP_SERVICE_PORT
          value: "587"
        - name: SMTP_SERVICE_USERNAME
          valueFrom:
            secretKeyRef:
              name: secrets-datatorgetbackend
              key: SMTP_USERNAME
        - name: SMTP_SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets-datatorgetbackend
              key: SMTP_PASSWORD
        - name: SENDGRID_APIKEY
          valueFrom:
            secretKeyRef:
              name: secrets-datatorgetbackend
              key: SENDGRID_APIKEY
        - name: OAUTH_AUTHORITY
          value: "http://datatorget2.helsingborg.se:30099"

      - name: betalningsapi
        image: datatorgetpoc/betalningsapi
        resources:
          limits:
            memory: "64Mi"
            cpu: "250m"
        ports:
        - containerPort: 30004
        env:
        - name: MESSAGE_SERVICE_HOST
          value: svc-rabbitmq
        - name: MESSAGE_SERVICE_PORT
          value: "5672"
        - name: MESSAGE_SERVICE_USERNAME
          valueFrom:
            secretKeyRef:
              name: secrets-datatorgetbackend
              key: MESSAGE_SERVICE_USERNAME
        - name: MESSAGE_SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets-datatorgetbackend
              key: MESSAGE_SERVICE_PASSWORD
        - name: MESSAGE_SERVICE_EXCHANGE
          value: "betalning"
        - name: MESSAGE_SERVICE_ENABLED
          value: "True"
        - name: OAUTH_AUTHORITY
          value: "http://datatorget2.helsingborg.se:30099"

      - name: valideringsapi
        image: datatorgetpoc/valideringsapi
        resources:
          limits:
            memory: "64Mi"
            cpu: "250m"
        ports:
        - containerPort: 30005
        env:
        - name: OAUTH_AUTHORITY
          value: "http://datatorget2.helsingborg.se:30099"

      - name: crmapi
        image: datatorgetpoc/crmapi
        resources:
          limits:
            memory: "64Mi"
            cpu: "250m"
        ports:
        - containerPort: 30006
        env:
        - name: OAUTH_AUTHORITY
          value: "http://datatorget2.helsingborg.se:30099"

      - name: kopplingstjanst
        image: datatorgetpoc/kopplingstjanst
        resources:
          limits:
            memory: "64Mi"
            cpu: "100m"
        env:
        - name: MESSAGE_SERVICE_HOST
          value: svc-rabbitmq
        - name: MESSAGE_SERVICE_PORT
          value: "5672"
        - name: MESSAGE_SERVICE_USERNAME
          valueFrom:
            secretKeyRef:
              name: secrets-datatorgetbackend
              key: MESSAGE_SERVICE_USERNAME
        - name: MESSAGE_SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets-datatorgetbackend
              key: MESSAGE_SERVICE_PASSWORD
        - name: BETALNINGSAPI
          value: "http://localhost:30004/api/v1"
        - name: BOKNINGSAPI
          value: "http://localhost:30001/api/v1"
        - name: OAUTH_AUTHORITY
          value: "http://datatorget2.helsingborg.se:30099"

      - name: identitysvc
        image: datatorgetpoc/identitysvc
        resources:
          limits:
            memory: "64Mi"
            cpu: "100m"
        env:
        - name: OAUTH_AUTHORITY
          value: "http://datatorget2.helsingborg.se:30099"
