apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      volumes:
      - name: volume-config-rabbitmq
        configMap:
            name: config-rabbitmq
      containers:
      - name: rabbitmq
        image: rabbitmq:management
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
          - name: http
            protocol: TCP
            containerPort: 15672
          - name: amqp
            protocol: TCP
            containerPort: 5672
        volumeMounts:
          - name: volume-config-rabbitmq
            mountPath: /etc/rabbitmq/config
            readOnly: true
        env:
          - name: RABBITMQ_ENABLED_PLUGINS_FILE
            value: /etc/rabbitmq/config/enabled_plugins
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: RABBITMQ_DEFAULT_USER
            valueFrom:
              secretKeyRef:
                name: secrets-datatorgetbackend
                key: MESSAGE_SERVICE_USERNAME
          - name: RABBITMQ_DEFAULT_PASS
            valueFrom:
              secretKeyRef:
                name: secrets-datatorgetbackend
                key: MESSAGE_SERVICE_PASSWORD
          - name: RABBITMQ_USE_LONGNAME
            value: "true"
          - name: K8S_SERVICE_NAME
            value: rabbitmq
