apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-mongo
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/datatorget/mongodata"
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volumeclaim-mongo
spec:
  storageClassName: manual
  volumeName: volume-mongo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
